### ISSUE TITLE
'pyltp.Postagger' object has no attribute 'load' 问题

### ISSUE THREAD

**Issue by Yuning-J** [lemonhu/open-entity-relation-extraction#16]
您好！感谢分享！我在运行的时候出现了以下问题（已经load model了）：
Start extracting...
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/_t/9brcc8tj3jbd5v9455w8bzh80000gp/T/jieba.cache
Loading model cost 0.989 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "extract_demo.py", line 19, in <module>
    nlp = NLP()
  File "../core/nlp.py", line 49, in __init__
    postag_flag = self.postagger.load(os.path.join(self.default_model_dir, 'pos.model'))
AttributeError: 'pyltp.Postagger' object has no attribute 'load'

请问您有什么建议吗？谢谢

**Comment by DeoooChen** [comment]
如果用的是pyltp0.4.0的话，是没有.load(model_path=path)这个方法的。现在改成了在初始化中就定义模型路径，例如：self.recognizer = NamedEntityRecognizer(os.path.join(self.default_model_dir, 'ner.model'))。在./code/core/nlp.py里面修改一下这几处代码即可
